### ISSUE TITLE
Language is not changed

### ISSUE THREAD

**Issue by cantalupo555** [cdgco/VestaWebInterface#100]
![](https://i.imgur.com/rkDBLCP.png)

The language is successfully changed, but the theme is not translated to the selected language.

**Comment by cdgco** [comment]
@cantalupo555 It appears that the language installation script I originally wrote no longer works. Are you using Ubuntu, Debian, CentOS or RHEL?

**Comment by cdgco** [comment]
@cantalupo555 Try running the command `sed -i 's/^# *\(pt_BR.UTF-8\)/\1/' /etc/locale.gen && locale-gen && service apache2 restart` and seeing if the page is translated.

**Comment by cantalupo555** [comment]
It works ... but he keeps cutting the first letters.
Tried to open in other browsers and presents the same problem.

![](https://i.imgur.com/Bv4zrhg.png)
![](https://i.imgur.com/DfjcmiM.png)

**Comment by cantalupo555** [comment]
I am using Ubuntu 18.04 (LXC)

**Comment by cantalupo555** [comment]
Just tested on another Ubuntu machine, presents the same problem
![](https://i.imgur.com/QfHCog8.png)

**Comment by cdgco** [comment]
@cantalupo555 Yes, I am experiencing this problem on my Debian servers as well, I have not had the time to diagnose the problem yet.

**Comment by cdgco** [comment]
It seems that the problem with translations being cut off were just errors in the configuration of the messages.po files. These should be fixed, at least for pt_BR in the latest commit efd7e403ef9f7917c57486c845755009f00b02f7. I also added many more translations in to pt_BR in this commit, although this locale is not complete yet.

**Comment by cdgco** [comment]
I changed the system that processes the translations from gettext to motranslator which allows for easier switching of locales and installation without locales or gettext extensions.

**Comment by cdgco** [comment]
Release v1.0.2 will be focused primarily on locale updates

**Comment by cantalupo555** [comment]
> Release v1.0.2 will be focused primarily on locale updates

thank you
