### ISSUE TITLE
APP list distance

### ISSUE THREAD

**Issue by cantalupo555** [cdgco/VestaWebInterface#101]
![](https://i.imgur.com/4JYpa80.png)

**Comment by cantalupo555** [comment]
The "softaculous" is very far from "phpmyadmin"

**Comment by cdgco** [comment]
@cantalupo555 Again, I do not have the time to come up with a comprehensive fix for this at the moment, but you should be able to change line 432 in your includes/includes.php file to ` if ($softaculousurl != '') { echo '<li style="height: 48px;"><a style="height: 48px;" href="' . $softaculousurl . '" target="_blank"><i style="top: -10px;" class="icon-softaculous">&#xe801;</i><span style="top: -21px;position: relative;" class="hide-menu">' . _("Softaculous") . '</span></a></li>';}` to fix this temporarily.
