### ISSUE TITLE
Backup Download not working

### ISSUE THREAD

**Issue by hkayaeu** [cdgco/VestaWebInterface#105]
**Server Environment**
```
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
WEB Server:     apache2:8080 (www-data)
SSL Support:    mod_ssl:8443
Proxy Server:   nginx:80
Proxy SSL:      nginx:443
Web Stats:      webalizer, awstats
FTP Server:     vsftpd
Mail Server:    exim4 + dovecot + clamav-daemon + spamassassin
Database:       mysql
DNS server:     bind9
CRON:           cron
Firewall:       iptables+ fail2ban
Backups:        local
Disk Quota:     no
Softaculous:    no
Version:        0.9.8
NAME           STATE    CPU  MEM   UPTIME
----           -----    ---  ---   ------
apache2        running  2.1  319   1153
nginx          running  0.1  35    1153
bind9          running  0    86    1153
exim4          running  0    6     35
dovecot        running  0    0     35
clamav-daemon  running  0.1  840   35
spamassassin   running  9.2  3102  35
mysql          running  9.2  3102  35
vsftpd         running  0    0     35
cron           running  0    0     35
iptables       stopped  0    0     0
fail2ban       running  4.9  123   10
```

**Client Environment**
If the error occurred within the Vesta Web Interface control panel, what was the client environment.

```
Operating System: MacOS / Windows
Web Browser: Safari / Chrome
Device: Mabook
```

**Describe the bug**
When a user wants to download a backup the screen asks for password and after that it forwards to port 8083 (vestacp) that is greeted with a invalid Cert, because server domainname and the panel domain name are different. Even if you ignore the cert error  the screen seems to be stuck in infinite loading. When you try to download the backup as admin that is logged in as the user the page forwards you to the VestaCP login screen.

**To Reproduce**
1. login to the Panel
2. go to backups
3. click on download and fill in the password

**Expected behavior**
The download should start

**Source code / logs / error code**
Nothing to find in the logs

**Comment by cdgco** [comment]
This seems to be a problem with the SSL on your old VestaCP control panel at port 8083 as VWI has to use the old control panel in order to load downloads. In order to fix this, either install a new SSL certificate on your VestaCP server or disable SSL for the old control panel.

**Comment by cdgco** [comment]
Please reopen this issue if you continue experiencing problems.
