### ISSUE TITLE
Updating mail account issue 

### ISSUE THREAD

**Issue by thecryptolive** [cdgco/VestaWebInterface#108]
**Server Environment**
Run the command `bash <(curl -s https://cdgco.github.io/debug)` and put the output below

```
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
WEB Server:     apache2:80 (www-data)
SSL Support:    mod_ssl:443
Web Stats:      webalizer, awstats
FTP Server:     proftpd
Mail Server:    exim4 + dovecot
Web Mail:       hostname + https://********.cloud/webmail
Database:       mysql
PMA URL:        https://********.cloud/phpmyadmin
CRON:           cron
Backups:        local
Disk Quota:     yes
Softaculous:    yes
Mail SSL:       admin:********.cloud
Version:        0.9.8
NAME     STATE    CPU  MEM   UPTIME
----     -----    ---  ---   ------
apache2  running  0    257   961
exim4    running  0    2     5319
dovecot  running  0    0     5408
mysql    running  4.4  1812  5408
proftpd  running  0    1     5408
cron     running  0    0     5408
```

**Client Environment**
If the error occurred within the Vesta Web Interface control panel, what was the client environment.

```
Operating System: MacOs and iOS
Web Browser: Safari, Chrome
Device: iMac, Macbook Pro, iPhone XR
```

**Describe the bug**
![5F38A213-1E0E-4DBE-A699-9C28E9F7F487](https://user-images.githubusercontent.com/61197903/76707075-c8fe0280-66c2-11ea-9e82-ea65785d2a45.jpeg)

I receive this error code even if modify are applied. I don't know why i receive error message when update done correctly

**To Reproduce**

**Expected behavior**

**Screenshots**

![D6DD168A-1023-4974-8F7D-2BFB28F8596C](https://user-images.githubusercontent.com/61197903/76707091-ddda9600-66c2-11ea-9793-fd4a60114211.jpeg)

**Source code / logs / error code**
Include any logs, source code or errors that would help diagnosing the problem.

2020-03-14 23:02:00 v-delete-mail-account-autoreply  'admin' '********.cloud' 'postmaster' [Error 3]
' [Error 2]17:36:41 v-delete-mail-account-alias  'admin' '********.cloud' 'hostmaster' '
' [Error 3]17:36:41 v-delete-mail-account-forward  'admin' '********.cloud' 'hostmaster' 'admin@********.cloud
2020-03-15 17:36:41 v-add-mail-account-forward  [Error 4  'admin' '********.cloud' 'hostmaster' 'admin@********.cloud']
2020-03-15 17:36:41 v-delete-mail-account-autoreply  'admin' '********.cloud' 'hostmaster' [Error 3]

**Additional context**

**Comment by thecryptolive** [comment]
Just note that i remove my domaine name and replace it by ********

**Comment by cdgco** [comment]
The main error here is that VestaCP was unable to update your mail account alias and is stating that the alias `hostmaster` is invalid. This seems like it may be a problem with VestaCP or your email server and sounds similar to the error described [here](https://forum.vestacp.com/viewtopic.php?t=6013) although there is no solution offered there.

My suggestion would be to start by rebuilding your mail domains using the `Rebuild Mail` button on the home screen of VWI, then restarting your server from the Admin -> Server section of the control panel, then attempting to update it again: 
<hr>

![rebuildmail](https://user-images.githubusercontent.com/13807630/77237104-62755a80-6b82-11ea-93c5-f585d6c3ca72.png)
<hr>

![restartserver](https://user-images.githubusercontent.com/13807630/77237238-9735e180-6b83-11ea-97d9-ed96d0259993.png)
<hr>

You can also run these commands in your terminal by executing `v-rebuild-mail-domains` and `reboot`

If that does not work, I would try updating the mail domain in the original VestaCP control panel to see if you are still getting an error on their panel. 

If so, I am unaware of any way to fix this error besides deleting the mail account and/or mail domain and adding a new account and/or domain.
