### ISSUE TITLE
Global page?

### ISSUE THREAD

**Issue by spike99** [cdgco/VestaWebInterface#119]
is there a global page? I want to add an ad on all pages

**Comment by cdgco** [comment]
There is not currently an option to add ads, I will add at least a footer option and possibly a header option later today. Thanks for the idea.

**Comment by cdgco** [comment]
@spike99 The option for custom ads is now available. You can install it immediately by doing a [manual install](https://vwi.cdgtech.one/#/manual-install) or you can wait until the next release which will include this feature. 

If you do a manual install, be sure to update your MySQL database either by using a clean table, or by using the command ```INSERT IGNORE INTO `vwi_config` (`VARIABLE`, `VALUE`) VALUES ('HEADER_AD', ''), ('FOOTER_AD', ''), ('ADMIN_ADS', 'true'), ('EXT_SCRIPT', '');``` to update your current table.
