### ISSUE TITLE
new bug when trying to change log png

### ISSUE THREAD

**Issue by Herd25** [cdgco/VestaWebInterface#123]
I was testing this interface because it seems to me a minimalist design to what vestacp offers by default but in the tests I found a small one, not to mention that many bugs in version 2.1.1 when making changes to the server system, the interface Now this panel is closed and does not allow access, it says that there was a problem in the server connection and the only thing that was done was to change the image of the banner and the favicon and some letters worked bine in version 1.0.1 but in this sending failures or just happened to me in case I leave it in consideration I will try to see what the specific bug is in order to give details of the failures that the interface has

**Comment by cdgco** [comment]
I just checked uploading images on one of my test environments and I was able to change the favicon, icon and logo with no error. What other settings did you change besides the images?

**Comment by Herd25** [comment]
Only that nothing else and it does not allow me to access the system I think that even the mysql corrupted me I have errors with the phpmyadmin and it does not give me access in case I think it has happened to me only I would have to reset vestacp from scratch

**Comment by Herd25** [comment]
the environment I use with this interface is centos 7 but in ubuntu I have not found that fault

**Comment by Herd25** [comment]
I tried again with a test interface from scratch and it returned to give the same failure when updating the favicon it seems that this version fails more with centos7 than with ubuntu What would be the most recommended to test in centos 7?

**Comment by cdgco** [comment]
I have tested on Ubuntu, Debian, CentOS and Windows, and this error is only happening on my CentOS environment as well, currently looking into it.

**Comment by cdgco** [comment]
@Herd25 What is your table name in MySQL?

**Comment by cdgco** [comment]
Changes to the logo system were made in commits 29c36c7 and 1fdcca2 which were released in [`v2.2.0`](https://github.com/cdgco/VestaWebInterface/releases/tag/v2.2.0). I'm assuming since there has been no response for a month that these commits solved the issue. If there is still a problem, please re-open this issue.
