### ISSUE TITLE
Running backup results in error in UI despite running properly

### ISSUE THREAD

**Issue by josh-abram** [cdgco/VestaWebInterface#124]
Under Manage Backups > "Schedule Backup" results in the following:

![image](https://user-images.githubusercontent.com/39235841/77843112-7efa3e00-71e5-11ea-847d-cfeae0532b26.png)

Despite this, the backup is executed and properly displays in the Backups section below when it's completed.

**Comment by cdgco** [comment]
The VestaCP API was returning 'OK' rather than '0'. Corrected by changing `'returncode' => $vst_returncode` to `'returncode' => 'yes'` in `add/backup.php`. Will be released in next minor version.

**Comment by josh-abram** [comment]
Tested & working (manually patched).
