### ISSUE TITLE
Error when edit Web domain with SSL

### ISSUE THREAD

**Issue by foudreclair** [cdgco/VestaWebInterface#137]
**Server Environment**
Run the command `bash <(curl -s https://cdgco.github.io/debug)` and put the output below

PHP 7.2.29-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar 20 2020 13:54:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.2.29-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
WEB Server:     apache2:8080 (www-data)
SSL Support:    mod_ssl:8443
Proxy Server:   nginx:80
Proxy SSL:      nginx:443
Web Stats:      webalizer, awstats
FTP Server:     vsftpd
Mail Server:    exim4 + dovecot + clamav-daemon + spamassassin
Database:       pgsql, mysql
DNS server:     bind9
CRON:           cron
Firewall:       iptables+ fail2ban
Backups:        local, ftp
Disk Quota:     yes
Softaculous:    yes
Language:       fr
Mail SSL:       admin:web1.hydrosaas.com
Vesta SSL:      admin:web1.hydrosaas.com
Version:        0.9.8
NAME           STATE    CPU  MEM   UPTIME
----           -----    ---  ---   ------
apache2        running  0.7  78    1
nginx          running  0    48    1
bind9          running  0    177   14
exim4          running  0    13    2
dovecot        running  0    0     8538
clamav-daemon  running  0    964   8538
spamassassin   running  1.3  3879  8538
postgresql     running  0    14    8538
mysql          running  1.3  3879  8538
vsftpd         running  0    0     8538
cron           running  0    0     8538
iptables       stopped  0    0     0
fail2ban       running  0.4  121   8538

**Client Environment**
If the error occurred within the Vesta Web Interface control panel, what was the client environment.

```
Operating System: Linux
Web Browser: Firefox
Device: Laptop
```

**Describe the bug**
When i edit a domain with a SSL domain the web server apache2 crash. 
Because the apache2 server can't find the SSL files. The ssl files are in the wrong directory : /home/admin he must be in /home/admin/conf/web

**To Reproduce**
1. Go to WEB
2. Click on Edit domain (the domain already have a SSL active)
3. Scroll down to Update domain (change anything)
Error 500 
Apr 21 20:21:14 web1.hydrosaas.com apachectl[10073]: SSLCertificateChainFile: file '/home/admin/conf/web/ssl.forum.hydrosaas.com.ca' does not exist or is empty

The error not appear when i edit the domain with the vestacp admin V1 !
I can reproduce the bug only in VWI

**Expected behavior**

**Screenshots**

2020-04-21 20:21:14 v-change-web-domain-sslcert  'admin' 'forum.hydrosaas.com' '/home/admin/' [Error 20]

**Additional context**

**Comment by cdgco** [comment]
The directory is correct, VWI is set to upload certificates to /home/admin as a temporary FTP accessible location, while the command `v-change-web-domain-sslcert` is supposed to process the certificates in /home/admin and move them into the correct directories such as /home/admin/conf/web/. 

Does this domain have a manual SSL certificate or one automatically generated by Let's Encrypt?

**Comment by foudreclair** [comment]
Thanks for this informations.
This domain are automatically generated by Let's Encrypt.

After the error i can't restart the apache because the files doesn't exist. The only solution is to delete the domain.

**Comment by cdgco** [comment]
It seems that there is a problem where it incorrectly tries to update an SSL certificate when updating domains but since an SSL certificate is already installed it overwrites it with empty data causing VestaCP to be unable to process the certificate and Apache2 to be unable to find it. I am currently working on an update to fix this.

**Comment by cdgco** [comment]
The problem should be fixed in the latest commit which will be included in the next update.
To fix this immediately, you can change `$domaindata` to `$domainssl` in lines 410, 417 & 424 of `edit/domain.php` as shown [here](https://github.com/cdgco/VestaWebInterface/commit/c77977459861de544feec1d3ac318f212c832258#diff-b37db7bd7d330dbf0636b1f635603bbd).

Please re-open the issue if this did not fix your problem.
