### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cdgco** [cdgco/VestaWebInterface#15]
Translate Vesta Web Interface based on settings specified in user profile.

**Comment by andresrobinson** [comment]
Hi, I can translate to Spanish and Portuguese if you want.

**Comment by cdgco** [comment]
I would love the help if you are willing. I am continuously adding terms to be translated, but have added your current translations.

**Comment by andresrobinson** [comment]
Sure, glad to help

**Comment by Efkovole** [comment]
> 
> 
> Přeložit webové rozhraní Vesta na základě nastavení zadaného v profilu uživatele.



> 
> 
> Rád bych rád pomohl, pokud jste ochotni. Neustále přidávám výrazy, které mají být přeloženy, ale přidaly vaše současné překlady.



> 
> 
> I would love the help if you are willing. I am continuously adding terms to be translated, but have added your current translations.

I have translated the files / locale / cz_CZ /
And if he switches to Czech, nothing will happen.

**Comment by cdgco** [comment]
@Efkovole if you are working on a local copy of Vesta Web Interface, you must restart apache / nginx / php-fpm in order for changes in localization to take place.

**Comment by cdgco** [comment]
To anyone who wants to help with translations, I am trying out POEditor rather than Poedit, which I have been using for the past few years. This software is better for collaboration, integrates directly with GitHub for ease of use and has free automatic translations for open source projects. 

The project is available at https://poeditor.com/join/project/ajbXtt6c51. 

I am currently awaiting approval of an Open Source license which will allow me to do more automatic translations. If / when this is approved, I should have v1.0.2 released shortly after with all languages translated.

I have completed the German and Spanish translations and am currently working on Brazilian Portuguese as well (more than 50% complete).

**Comment by cdgco** [comment]
Closed with 49af673861b8d557546ca6ce038f0190b09fb565
