### ISSUE TITLE
Ive tried installing this thing 10 times today and keep getting 500 errors

### ISSUE THREAD

**Issue by Stage4000** [cdgco/VestaWebInterface#150]
Ive successfully installed this on a different machine, not sure why im getting so many issues with this install on a different machine but its been an all day affair at this point. This is my log from the latest attempt at installing today.

[Fri Jul 30 21:12:33.513343 2021] [php:warn] [pid 9122] [client ---------:51476] PHP Warning:  Undefined variable $connection in /home/admin/web/panel.stage4000.com/public_html/install/step2.php on line 90, referer: https://panel.stage4000.com/install/
[Fri Jul 30 21:12:33.513402 2021] [php:warn] [pid 9122] [client ----------:51476] PHP Warning:  Undefined variable $connection in /home/admin/web/panel.stage4000.com/public_html/install/step2.php on line 91, referer: https://panel.stage4000.com/install/
[Fri Jul 30 21:13:39.085893 2021] [php:warn] [pid 9120] [client --------:52140] PHP Warning:  Undefined variable $KEY3 in /home/admin/web/panel.stage4000.com/public_html/install/install.php on line 33, referer: https://panel.stage4000.com/install/step3.php
[Fri Jul 30 21:13:39.085942 2021] [php:warn] [pid 9120] [client --------:52140] PHP Warning:  Undefined variable $KEY4 in /home/admin/web/panel.stage4000.com/public_html/install/install.php on line 33, referer: https://panel.stage4000.com/install/step3.php
[Fri Jul 30 21:13:39.235686 2021] [php:warn] [pid 9120] [client ------------:52140] PHP Warning:  Undefined variable $KEY3 in /home/admin/web/panel.stage4000.com/public_html/install/install.php on line 33, referer: https://panel.stage4000.com/install/step3.php
[Fri Jul 30 21:13:39.235700 2021] [php:warn] [pid 9120] [client ---------:52140] PHP Warning:  Undefined variable $KEY4 in /home/admin/web/panel.stage4000.com/public_html/install/install.php on line 33, referer: https://panel.stage4000.com/install/step3.php
[Fri Jul 30 21:14:13.923849 2021] [php:error] [pid 12182] [client ------------:52526] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php:49\nStack trace:\n#0 /home/admin/web/panel.stage4000.com/public_html/includes/includes.php(49): mysqli_query()\n#1 /home/admin/web/panel.stage4000.com/public_html/login.php(27): require('...')\n#2 {main}\n  thrown in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php on line 49, referer: https://panel.stage4000.com/install/complete.html
[Fri Jul 30 21:14:15.345941 2021] [php:error] [pid 9119] [client ------------:52552] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php:49\nStack trace:\n#0 /home/admin/web/panel.stage4000.com/public_html/includes/includes.php(49): mysqli_query()\n#1 /home/admin/web/panel.stage4000.com/public_html/login.php(27): require('...')\n#2 {main}\n  thrown in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php on line 49, referer: https://panel.stage4000.com/install/complete.html
[Fri Jul 30 21:14:17.837572 2021] [php:error] [pid 9121] [client ------------:52564] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php:49\nStack trace:\n#0 /home/admin/web/panel.stage4000.com/public_html/includes/includes.php(49): mysqli_query()\n#1 /home/admin/web/panel.stage4000.com/public_html/index.php(28): require('...')\n#2 {main}\n  thrown in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php on line 49
[Fri Jul 30 21:14:18.188656 2021] [php:error] [pid 9122] [client -----------------:52570] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php:49\nStack trace:\n#0 /home/admin/web/panel.stage4000.com/public_html/includes/includes.php(49): mysqli_query()\n#1 /home/admin/web/panel.stage4000.com/public_html/index.php(28): require('...')\n#2 {main}\n  thrown in /home/admin/web/panel.stage4000.com/public_html/includes/includes.php on line 49

**Comment by cdgco** [comment]
What version of PHP are you using and are you using PHP or PHP-FPM? The first thing I would try is to change the line `$configstyle = '1';` to `$configstyle = '2';` in `includes/includes.php` (line 36) to see if that makes a difference. I don't think I made any bug fixes that relate to this issue, but you could try using the devinstall command to get the latest version with unreleased bug fixes: `bash <(curl -s https://cdgco.github.io/devinstall)`

**Comment by Stage4000** [comment]
Its a fresh vesta install, I did try configstyle change on one install and it didnt seem to help anything guess ill try devinstall now

**Comment by cdgco** [comment]
Are you using PHP 5, 7 or 8 / can you run the debug command `bash <(curl -s https://cdgco.github.io/debug)`?

**Comment by Stage4000** [comment]
max_execution_time   30
max_input_time       60
memory_limit         128M
error_reporting      E_ALL         &  ~E_DEPRECATED  &  ~E_STRICT
display_errors       Off
post_max_size        8M
upload_max_filesize  2M
config_path          /etc/php.ini
CentOS Linux release 7.9.2009 (Core)
WEB Server:     httpd:8080 (apache)
SSL Support:    mod_ssl:8443
Proxy Server:   nginx:80
Proxy SSL:      nginx:443
Web Stats:      webalizer, awstats
FTP Server:     vsftpd
Mail Server:    exim + dovecot + clamav + spamassassin
Database:       mysql
DNS server:     named
CRON:           crond
Firewall:       iptables+ fail2ban
Backups:        local
Disk Quota:     no
Softaculous:    yes
Mail SSL:       admin:stage4000.com
Vesta SSL:      admin:panel.stage4000.com
Version:        0.9.8
NAME          STATE    CPU  MEM   UPTIME
----          -----    ---  ---   ------
httpd         running  0    83    34
nginx         running  0    13    34
named         running  0    311   34
exim          running  0    1     50
dovecot       running  0    0     50
clamd         running  0.4  1258  50
spamassassin  running  0.9  5025  50
mariadb       running  0    1089  50
vsftpd        running  0    1     8
crond         running  0    1     50
iptables      running  0    0     0
fail2ban      stopped  0    0     0

PHP 8.0.9

**Comment by Stage4000** [comment]
and still 500s on devfull

**Comment by cdgco** [comment]
Alright, that's what I was worrying about. This error is related to PHP 8 which is not currently supported. I don't plan on adding new features to this project as I am shifting toward HestiaCP and don't have much time to work on things right now, so I will likely not be updating to PHP 8. If you want to get it working I would recommend rolling back to PHP 7 or installing MultiPHP for VestaCP (https://forum.vestacp.com/viewtopic.php?t=12737) so that you can put this domain on a specific PHP version.

**Comment by Stage4000** [comment]
Thats odd that 2 different vesta installs gave me 2 different PHP versions only 1 day apart.

**Comment by Stage4000** [comment]
I might just go with Hestia, the only reason ive stayed with Vesta so long is because theres just better documentation available for it than hestia.

**Comment by cdgco** [comment]
It must just be the latest version. Vesta hasn't released an update since January of last year. I wouldn't recommend using it anymore due to security holes and lack of updates which is why I am switching to HestiaCP which includes MutiPHP by default.

**Comment by cdgco** [comment]
Vesta does have much better documentation, but from what I've found, almost everything works the exact same in Hestia including API calls.

**Comment by Stage4000** [comment]
I also like the idea of working with ubuntu again, im much more familiar with it than centos, and if you have tried using vesta on ubuntu lately its not great.

**Comment by cdgco** [comment]
I haven't done a VestaCP install in a while but I typically use Debian as I run into issues with existing applications when trying to install VestaCP on Ubuntu.

**Comment by Stage4000** [comment]
I hope hestia is a little more friendly to ubuntu?

**Comment by cdgco** [comment]
I can't remember if I ran into any issues with the install, but I believe it was more friendy. I currently have 2 Ubuntu servers running HestiaCP.

**Comment by Stage4000** [comment]
Thanks, you can close this at your convenience. Any further tickets can be opened in the other repo.
