### ISSUE TITLE
Can't seem to login?

### ISSUE THREAD

**Issue by TomAlderson** [cdgco/VestaWebInterface#152]
I've installed everything the standard way and followed the steps through, I can login to my standard VestaCP but using the VestaWebInterface I'm told wrong password, then when I attempt a password reset, I enter the code then get asked to enter my password, I do but it just refreshes and my password never changes?

Anyone else had this experience?

**Comment by cdgco** [comment]
If you installed using the password or api key, I would recommend reinstalling using the other to see if that changes anything. Also, check your PHP logs to see if there are any errors connecting to the VestaCP api.

**Comment by TomAlderson** [comment]
@cdgco Thanks for offering your help but I'm still in a bind.

The only error I am getting back is Error 3 - looks like it thinks the user does not exist in VestaCP even though the user definitely does. My VestaCP has recently upgraded to the latest version so not sure if it's anything to do with that.

I did try an API key too as an alternative but got the same result - very strange behaviour. I'm going to keep investigating and see if I can figure out what is happening. For clarification, this is what I get from the logs:

>  v-list-user  'MhXSltve237rhR' 'json'

The following steps are what I've just performed: -

1. Attempt to login with VestaCP 'admin' and password.
2. Receive incorrect login message.
3. Head to the forgot password page and enter 'admin' username.
4. Received an email with 'NOLANGUAGEDEFINED plastered all over it, strange.
5. Repeat the forgot password page again.
6. Receive the correct 'Password Reset' email this time.
7. Head to the 'Reset' page and enter code from email.
8. Confirm my new password in the form and submit.
9. Then get redirected back to the 'Reset' page where you must enter a code before setting a new password.

The only logs I received during this time were: -

> 2021-11-11 08:57:35 v-list-user  'MhXSltve237rhR' 'json' [Error 3]
> 2021-11-11 09:00:09 v-add-letsencrypt-domain  'admin' 'server.example.co.uk' 'www.server.example.co.uk' 'yes' 'yes' [Error 15]

What's odd is that 'MhXSltve237rhR' is actually the password reset code I was given, does this seem correct behaviour? I'm a bit lost on the LetsEncrypt error but my first assumption is that it's trying to go to www.server.example.com rather than just server.example.com

Sorry for the essay, hope it makes life easier to understand what's happening.

**Comment by TomAlderson** [comment]
Managed to fix this in the end - it was related to the SSL issue but after that was fixed I reinstalled and it just worked (with a different suffix for the database tables). Thanks.
