### ISSUE TITLE
Login or Index doesn't work

### ISSUE THREAD

**Issue by ReNNoN** [cdgco/VestaWebInterface#23]
"Loading dashboard..."

Workly perfect for a 2 hours, but incomprehensibly now don't load index.php, load a serveral time with the message "Loading dashboard" in green color, and then emit a "500 - Internal Server Error".

Any idea?

thanks u

**Comment by cdgco** [comment]
Could you edit the `.htaccess` file and change the line `php_flag display_errors Off` to `php_flag display_errors On` then reload the page and tell me what the error is?

-Carter

**Comment by ReNNoN** [comment]
Notice: Undefined index: username in /home/admin/web/mydomain.com/public_html/vwi/includes/config.php on line 96

Notice: Undefined index: loggedin in /home/admin/web/mydomain.com/public_html/vwi/includes/config.php on line 97

I tried put a vwi installation on public_html folder, same error in the two places, vesta/web and public_html.

thx u!

**Comment by cdgco** [comment]
Are those errors listed on the login page or on the page once you attempt to login?

The errors you listed are known warnings and do not cause actual problems or 500 errors, so there must be a problem somewhere else.

**Comment by ReNNoN** [comment]
Honestly, I've been trying to make it work for days, but I do not succeed.


It's strange, because VWI worked perfectly until 2 days ago, but for some reason it did not work anymore.

He tried everything, uninstall, install, many times.

All the dependencies are installed and functioning well.

Ubuntu Server 16.04 updated.

Sometimes it loads the login.php but not the index.php (it is frozen in "Loading Dashboard") and other times it does not load the login.php (White screen and 500 error in timeout).

Is VWI compatible with the IONCube extension? (needed for WHMCS)?

Have not you had any problems before?

Thank you

**Comment by cdgco** [comment]
VWI should be compatible with IONCube and I have not seen this problem before. It may be beneficial for you to tell me the URL of your installation or allow me access to view your installation. If you would like, feel free to email me at carter@cdgtech.one. Also, you may want to try a fresh install in a new directory or domain, and make sure you are using the installation command or newest release (0.3.1).
