### ISSUE TITLE
Cannot install on Ubuntu 16.04?

### ISSUE THREAD

**Issue by aidan-casey** [cdgco/VestaWebInterface#32]

**Comment by cdgco** [comment]
The majority of VWI development is done on Ubuntu 16.04 and the VWI demo is hosted on an Ubuntu 16.04 server so there should be no problem with installing on 16.04. 

Did you follow the step-by-step directions on https://cdgtech.one/vwi/docs.php#automatic ? 

Could you please add a description of the problem or a specific error code to help further solve this problem?

**Comment by cdgco** [comment]
Closing as there has been no response. If you are still experiencing problems, reopen the issue or contact support@cdgtech.one.
