### ISSUE TITLE
Deleting domain

### ISSUE THREAD

**Issue by aidan-casey** [cdgco/VestaWebInterface#33]
When deleting a domain "Successfully created!" is displayed.

**Comment by cdgco** [comment]
I am not seeing this issue in the code, or am not exactly sure of how to recreate it. Could you please tell me from which page you are attempting to delete the domain?

**Comment by cdgco** [comment]
Closing as there has been no response and issue seems to be a mistake or fixed bug from previous versions. If you are still experiencing problems, reopen the issue or contact support@cdgtech.one.
