### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by vstock28021** [cdgco/VestaWebInterface#38]
It would be nice in the admin panel for the admin user to be able to do things like change the name of the site, the logo, turn on/off user registrations, etc.

I use VestaCP as a HCP for my side business. I would love to see CDG VWI as something I can hand to my clients that has some type of plugin system or is semi modular so I don't have to spend a week coding hacks to add things like Net2FTP/Angular [FileManager](https://github.com/joni2back/angular-filemanager) into the interface. You have a good start on a great product and I commend you.

However as I am not doing Shared Hosting with VestaCP disabling sign ups is huge for me. If I have to hack the code to do this everytime an update comes out then to me it's no different then spending a week hacking the core web interface of VestaCP.

**Comment by cdgco** [comment]
Thank you for your insight and recommendations. I agree that the configuration should be available within the admin panel and I will add that to the todo list along with adding the option to disable signups within the config file and the soon-to-come admin config page.

As for plugins, I have recently introduced a plugin system with a file manager plugin already available.

[Plugin System](https://github.com/cdgco/VestaWebInterface/tree/master/plugins)
[File Manager]( https://github.com/cdgco/vwi-ftp)

While I have only created a plugin for MonstaFTP, the integration is seamless and the plugin page offers detail on how to create plugins, if you so desire.

If you have any further recommendations, please reply back or contact me at carter@cdgtech.one as I would love to improve your experience and make this a viable product for you.
