### ISSUE TITLE
Fuzzy Instructions

### ISSUE THREAD

**Issue by ubuntume** [cdgco/VestaWebInterface#53]
Im under the impression that this panel is suppose to be a "replacement" for the default vestacp theme. I love the mission, ui, and the extend-ability I am seeing already. I have a few questions that the documentation did not make clear enough for my understanding.

Im under the impression that I create a domain or subdomain with nothing in it. Then I run the auto install command (by preference). Once the /install is up I ensure that all checks are go. Then the database section is what I misunderstood. Is this any database I want or is this suppose to be connected to the root user (or equivalent)? 

Also is the domain I enter in during the CLI portion suppose to be the domain to my original Vestacp or the domain Im installing the VWI?

In my situation I created a new DB, New Domain, Got all green lights and then stuck on step2.

**Comment by cdgco** [comment]
Yes, everything you are doing seems to be correct.

The database can be any database and any user that has read and write access to the specified database (not just root), so you could use an existing database and user or create a new database and user with access to the database. I would recommend not using the root user (although it does work) for added security. 

The prefix selection allows you to change the table name in your database to ensure compatibility in the off-chance that you are using an existing database with the same table name or you would like to run multiple VWI installations from the same database.

The domain name entered in the CLI installer is supposed to be the domain you are installing VWI in, and the only place where this is used is for replacing the Control Panel link within the Softaculous Application, although this feature is not a great implementation, and I plan on removing it or replacing it in the future.

Thank you for bringing this to my attention, I will update the documentation and focus on a more intuitive installation process.

If you need any assistance in your installation, let me know!
