### ISSUE TITLE
Error on Mail Account Creating

### ISSUE THREAD

**Issue by Plata-0-Plomo** [cdgco/VestaWebInterface#66]
Hello!

When I created the email account, I received the following error:
`Parse error: syntax error, unexpected ';' in /home/hosting/web/panel.plomo.gq/public_html/create/mailaccount.php on line 125`

I solved this in the following way:
/create/mailaccount.php
on 125 line 
    addslashes(
replace to 
    addslashes();

But I'm not sure if this is the right and safe solution

**Comment by cdgco** [comment]
It looks like I accidentally left that there, that `addslashs(` line can actually be removed entirely. I have removed it from the latest release.
