### ISSUE TITLE
VWI-Billing, sql database

### ISSUE THREAD

**Issue by Plata-0-Plomo** [cdgco/VestaWebInterface#67]
Hello!

I installed the billing plugin, but unfortunately it does not work.
Returns errors related to queries in the database. I looked at the code and saw that there are queries to the following tables:
billing-config
billing-plans

I do not have these tables in the database. In the plugin, I also found no place to create tables. Where can they be taken?

Why there was such error, it can because of type of installation?

**Comment by cdgco** [comment]
This plugin is in development, and is marked as WIP - Work In Progress as it is not ready to be installed yet.

**Comment by cdgco** [comment]
For future reference, please open plugin related issues in their designated repositories: [cdgco/vwi-billing](https://github.com/cdgco/vwi-billing).
