### ISSUE TITLE
Additional FTP greyed out?

### ISSUE THREAD

**Issue by cvexer2** [cdgco/VestaWebInterface#80]
the additional ftp option for web is greyed out cant click on the check box ,

but if I go back to the original old panel I can create with no issue.

![ftp-vestacp-greyed-out](https://user-images.githubusercontent.com/45900225/51340952-421dad80-1a5e-11e9-8475-4c5ce368dfb5.png)
thanks for any help that you can give on this issue.

**Comment by cdgco** [comment]
Additional FTP is currently in development and is planned to be released in the next version. If you manually install the current development build, you can use Additional FTP, although there are still bugs in the system.
