### ISSUE TITLE
Failed to connect to server. Please check config.

### ISSUE THREAD

**Issue by Caetano1149621111** [cdgco/VestaWebInterface#81]
v0.5.4-Beta

### OS / Environment

```
Linux aeon.datacenter.gru.br 2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Apr 11 17:13:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Summary of the problem

Same problem a last post. See http://www.datacenter.gru.br/login.php
"Failed to connect to server. Please check config."

### Steps to reproduce the behavior

Try login.

### Source code / logs / error code

Failed to connect to server. Please check config.

**Comment by Caetano1149621111** [comment]
![image](https://user-images.githubusercontent.com/9559838/51434355-e9a90480-1c45-11e9-9036-650e6d692554.png)

**Comment by cdgco** [comment]
This means that either the host address, port, ssl, username or password to your VestaCP server is incorrect. Please check your MySQL database and correct any errors. Visit https://vwi.cdgtech.one/#/web-config for more info.

**Comment by roxyschram** [comment]
I'm having the same issue. After install, I can log in. I can browse around. After 5 minutes logged it I get logged out and it says failed to connect to server. Please check config.

**Comment by roxyschram** [comment]
Just tried something, changing host from the URL to localhost fixed my issue. Had to change through phpmyadmin

**Comment by cdgco** [comment]
That sounds like it could be an error with the way the domain was entered, assure that you do not enter "https://" or the following "/". You could also try entering the IP address of your VestaCP server to see if this is actually an error with connecting to Vesta or with the way the address is being entered.
