### ISSUE TITLE
Can't edit web/dns stuff

### ISSUE THREAD

**Issue by roxyschram** [cdgco/VestaWebInterface#82]
### OS / Environment

```
CentOS Linux release 7.6.1810 (Core)

Linux ###.######.com 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

VWI 0.5.4 beta

VestaCP

PHP 7.0

nGinx

Apache
```

### Summary of the problem
Unable to display or edit entries in WEB/DNS/BACKUP from VWI. Having to log into VestaCP to make those changes. Also, click on username in sidebar does nothing. 

### **ALL SOFTWARE IS UP TO DATE. What ever the latest version is, that is what I have. Updates run daily**

![vwi01](https://user-images.githubusercontent.com/20067948/52090654-03204980-2580-11e9-8154-488c7c57707f.jpg)
![vwi02](https://user-images.githubusercontent.com/20067948/52090655-03204980-2580-11e9-82ce-3734f5011354.jpg)

**Comment by roxyschram** [comment]
So I changed the theme from the user account and NOW it won't connect to Vesta again saying the check config

**Comment by cdgco** [comment]
I presume this error was either a configuration error or has been fixed in an update. Please reopen this ticket if you still have an issue.
