### ISSUE TITLE
Error with functionally on newerest version VestaCP

### ISSUE THREAD

**Issue by Krzysztofeqq** [cdgco/VestaWebInterface#91]
### OS / Environment
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
Linux vmi276970.contaboserver.net 4.15.18-16-pve #1 SMP PVE 4.15.18-41 (Tue, 18 Jun 2019 07:36:54 +0200) x86_64 GNU/Linux
```

### Summary of the problem
Hello, i installed interface and have problems with functionally
### Steps to reproduce the behavior
PHP error show, check database, check packages
### Source code / logs / error code
Not Showing Domains in /list/web.php
Error with adding ssl

![1](https://user-images.githubusercontent.com/44102524/60304328-664cb700-9939-11e9-8f9e-6475f56ea43a.png)
![2](https://user-images.githubusercontent.com/44102524/60304329-664cb700-9939-11e9-8698-128e27a05a7b.png)

**Comment by cdgco** [comment]
@Krzysztofeqq It looks like you had some kind of debugging enabled which was conflicting with the PHP rendering. If you are still having problems let me know / reopen the issue.

**Comment by Krzysztofeqq** [comment]
I repaired, errors. :+1:  thanks, your interfeace been beatfull, please add with backround particles red and black color <3

**Comment by Krzysztofeqq** [comment]
@cdgco Can I create a Polish version of your interface as a Polish user?

**Comment by cdgco** [comment]
@Krzysztofeqq Thank you. If you would like to help translate VWI, there are preset locale files in the [/locale](https://github.com/cdgco/VestaWebInterface/blob/master/locale) folder. The empty polish translation files are located in the [pl_PL/LC_MESSAGES](https://github.com/cdgco/VestaWebInterface/tree/master/locale/pl_PL/LC_MESSAGES) folder. I recommend using the tool [poedit](https://poedit.net/) to open and edit translation files.

**Comment by Krzysztofeqq** [comment]
@cdgco really? I translate in PHP files, :D I did not know it was empty: D I'm taking on the translation because I need it myself.

**Comment by Krzysztofeqq** [comment]
@cdgco I can add with created by ... that Polish translation created by my name and surname (Nickname)?

**Comment by cdgco** [comment]
@Krzysztofeqq Yeah, most of the translation files are empty as neither I or anyone else has taken the time to do the translations. I use .po / .mo files for translation because it allows the PHP files to remain the same and uses a the PHP gettext extension to manage the translation on a per session basis. 

You can add whatever name or credit you would like.

**Comment by Krzysztofeqq** [comment]
@cdgco I got lost in the action because I saw this file, but I thought it was full: D I've already translated 76 words about 600

**Comment by Krzysztofeqq** [comment]
And I have a question, could I have some contact with you? Not by GitHub

**Comment by cdgco** [comment]
@Krzysztofeqq You can contact me directly by email if you wish, carter@cdgtech.one

**Comment by Krzysztofeqq** [comment]
> @Krzysztofeqq You can contact me directly by email if you wish, [carter@cdgtech.one](mailto:carter@cdgtech.one)

Okey, i writing mails from email contact@krzysztofeqq.tk

**Comment by Krzysztofeqq** [comment]
How to load language?

**Comment by cdgco** [comment]
@Krzysztofeqq Are you asking how to load it into poedit or how to change the language in VWI?

**Comment by Krzysztofeqq** [comment]
> @Krzysztofeqq Are you asking how to load it into poedit or how to change the language in VWI?

VMI

**Comment by cdgco** [comment]
@Krzysztofeqq You should be able to change the default language in the admin settings page, `/admin/list/settings.php`. You can change the language for the current user in the account settings page, `/profile.php?settings=open`.

I have had some trouble in the past getting translations to work on some systems and I haven't tested the function in a long time since the translations were never completed, so let me know if it doesn't work.

**Comment by Krzysztofeqq** [comment]
help me in https://github.com/cdgco/VestaWebInterface/issues/92 ( Panel on Nginx )
