### ISSUE TITLE
Error with ssl certificates and update domains

### ISSUE THREAD

**Issue by Krzysztofeqq** [cdgco/VestaWebInterface#92]
### OS / Environment

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
Linux vmi276970.xad.net 4.15.18-16-pve #1 SMP PVE 4.15.18-41 (Tue, 18 Jun 2019 07:36:54 +0200) x86_64 GNU/Linux
```

### Summary of the problem

SSL from Cloudflare, Let's Encrypt and other not working
Error Updating Web Domain
Please try again or contact support.
(E: 0.0.0.0.0.0.2.0.0.0.0.0)

### Steps to reproduce the behavior
Error Updating Web Domain
Please try again or contact support.
(E: 0.0.0.0.0.0.2.0.0.0.0.0)

### Source code / logs / error code
Error Updating Web Domain
Please try again or contact support.
(E: 0.0.0.0.0.0.2.0.0.0.0.0)

**Comment by Krzysztofeqq** [comment]
And bug on add package, not showing dns teamplates, and how to remove proxy teamplate?

**Comment by cdgco** [comment]
@Krzysztofeqq The error codes are listed on the VWI Documentation on the page [error codes](https://vwi.cdgtech.one/#/errors). In this case the error code is reporting that there was an invalid argument provided when deleting or adding a web domain statistics user. 

Please include the corresponding error as shown in the `/usr/local/vesta/log/error.log` file if you would like me to further troubleshoot this error.

As for the DNS templates problem, I am not sure and would have to spend some time working on that to find out.

Templates such as the proxy template are controlled only through the VestaCP source files and must be changed in the `/usr/local/vesta/data/templates/` directory you can read more about VestaCP templates [here](https://vestacp.com/docs/#template-description).

**Comment by Krzysztofeqq** [comment]
> @Krzysztofeqq The error codes are listed in the VWI Documentation on the page [error codes](https://vwi.cdgtech.one/#/errors). In this case the error code is reporting that there was an invalid argument provided when deleting or adding a web domain statistics user.
> 
> Please include the corresponding error as shown in the `/usr/local/vesta/log/error.log` file if you would like me to further troubleshoot this error.
> 
> As for the DNS templates problem, I am not sure and would have to spend some time working on that to find out.
> 
> Templates such as the proxy template are controlled only through the VestaCP source files and must be changed in the `/usr/local/vesta/data/templates/` directory. You can read more about VestaCP templates [here](https://vestacp.com/docs/#template-description).

I send link to logs to your email.

**Comment by Krzysztofeqq** [comment]
You help me? or not help?

**Comment by cdgco** [comment]
@Krzysztofeqq Sorry, I am at work right now and don't have much time to check Github.

It looks like I misread the error code and it is actually a problem with Let's Encrypt. Let's Encrypt and other VestaCP functions are unable to connect to the website you are trying to enable SSL on. 

I believe this is an error with the templates you were speaking of earlier. It seems you need the proxy template in order for Let's Encrypt to enable SSL on your website but I am not sure.

Regardless, this is an error with your domain configuration and VestaCP, not VWI so I am unable to provide much support besides that. 

I recommend changing the templates and disabling the re-enabling Let's Encrypt Support, but you should start a topic at the [VestaCP Forum](https://forum.vestacp.com/index.php) to get support from the VestaCP team.
