### ISSUE TITLE
Please help me with install interface on debian 9

### ISSUE THREAD

**Issue by CodeczeQ** [cdgco/VestaWebInterface#94]
Please type commands to install interface

**Comment by cdgco** [comment]
Please refer to the [documentation](https://vwi.cdgtech.one/#/auto-install) for installation instructions.

**Comment by Krzysztofeqq** [comment]
Not working, get in webinterface errors :/

**Comment by cdgco** [comment]
Please either use the [manual installation](https://vwi.cdgtech.one/#/manual-install) method or provide some detail about the problem.

I can't do anything if you don't give any information on the problem.
