### ISSUE TITLE
 portal sections DB, DNS, WEB do not appear

### ISSUE THREAD

**Issue by mikeleord** [cdgco/VestaWebInterface#97]
**Server Environment**
Run the command `php -v && lsb_release -a && /usr/local/vesta/bin/v-list-sys-config` and put the output below

```
PHP 7.3.8 (cli) (built: Jul 30 2019 09:26:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
-bash: lsb_release: command not found

```

**Client Environment**
If the error occurred within the Vesta Web Interface control panel, what was the client environment.

```
Operating System: centos 7.6
Web Browser: all
Device: PC
```

**Describe the bug**
Hello
I installed version 1, in the portal sections DB, DNS, WEB do not appear, I manually entered the url but by error 404.
How could I solve it?
thank you so much

**Screenshots**
![vesta](https://user-images.githubusercontent.com/42770845/62429686-5be0c280-b71a-11e9-9ad7-0888f682605a.png)
![vesta2](https://user-images.githubusercontent.com/42770845/62429710-dc9fbe80-b71a-11e9-9b9a-521a3bf32495.png)

**Comment by cdgco** [comment]
@mikeleord Hello, could you try running the command `/usr/local/vesta/bin/v-list-sys-config` and send the results, it seems the output is missing from your post. Could you also try visiting http://10.29.22.212/list/web.php and seeing what happens?

**Comment by mikeleord** [comment]
Hello sorry the delay, on /list/web.php gives me error 403 forbidden.
here is the excuse command I had not attached:

WEB Server:     httpd:8080 (apache)
SSL Support:    mod_ssl:8443
Proxy Server:   nginx:80
Proxy SSL:      nginx:443
Web Stats:      webalizer, awstats
FTP Server:     proftpd
Mail Server:    exim + dovecot + clamav + spamassassin
Database:       mysql
DNS server:     named (cluster)
CRON:           crond
Firewall:       iptables+ fail2ban
Backups:        local
Disk Quota:     yes
Softaculous:    yes
Version:        0.9.8

**Comment by cdgco** [comment]
@mikeleord Alright, thank you. VWI seems to be failing to identify apache2, bind9, or mysql.

Please create a new file in the base directory of your VWI installation (the same directory as the index.php file) called test.php with the following contents, then visit http://10.29.22.212/test.php and send the results:
```
<?php

require("includes/includes.php");

$vcpservices = curl_init();

curl_setopt($vcpservices, CURLOPT_URL, $vst_url);
curl_setopt($vcpservices, CURLOPT_RETURNTRANSFER,true);
curl_setopt($vcpservices, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($vcpservices, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($vcpservices, CURLOPT_POST, true);
curl_setopt($vcpservices, CURLOPT_POSTFIELDS, http_build_query(array('hash' => $vst_apikey, 'user' => $vst_username,'password' => $vst_password,'cmd' => 'v-list-sys-services', 'arg1' => 'json')));
$servicedata = curl_exec($vcpservices);

print_r($servicedata);

function checkServicex($requestedService) {
    global $servicedata;
    if($requestedService[0] == '/') {return preg_match($requestedService, $servicedata);}
    if( strpos($servicedata, $requestedService) !== false ) { return true; }
    else { return false; }

}
print_r("\n\nApache2 Check: " . checkServicex('apache2'));
```

**Comment by mikeleord** [comment]
hi,
thanks for the help, here is the result:

{ "httpd": { "SYSTEM": "web server", "STATE": "running", "CPU": "0", "MEM": "497", "RTIME": "102" }, "nginx": { "SYSTEM": "reverse proxy", "STATE": "running", "CPU": "0", "MEM": "39", "RTIME": "102" }, "named": { "SYSTEM": "dns server", "STATE": "running", "CPU": "0.5", "MEM": "1486", "RTIME": "102" }, "exim": { "SYSTEM": "mail server", "STATE": "running", "CPU": "0", "MEM": "1", "RTIME": "102" }, "dovecot": { "SYSTEM": "pop/imap server", "STATE": "running", "CPU": "0", "MEM": "0", "RTIME": "102" }, "clamd": { "SYSTEM": "email antivirus", "STATE": "running", "CPU": "0.7", "MEM": "819", "RTIME": "102" }, "spamassassin": { "SYSTEM": "email antispam", "STATE": "running", "CPU": "1.3", "MEM": "6748", "RTIME": "102" }, "mariadb": { "SYSTEM": "database server", "STATE": "running", "CPU": "0", "MEM": "1830", "RTIME": "102" }, "proftpd": { "SYSTEM": "ftp server", "STATE": "running", "CPU": "0", "MEM": "1", "RTIME": "102" }, "crond": { "SYSTEM": "job scheduler", "STATE": "running", "CPU": "0", "MEM": "1", "RTIME": "102" }, "iptables": { "SYSTEM": "firewall", "STATE": "running", "CPU": "0", "MEM": "0", "RTIME": "0" }, "fail2ban": { "SYSTEM": "brute-force monitor", "STATE": "running", "CPU": "0.1", "MEM": "583", "RTIME": "102" } } Apache2 Check:

**Comment by cdgco** [comment]
@mikeleord It seems that either VestaCP has changed their naming conventions or CentOS uses different naming than Ubuntu and Debian. 

Regardless, I just updated the software so that it should fix this error with CentOS. Please replace your `includes/includes.php` file with the new version from https://raw.githubusercontent.com/cdgco/VestaWebInterface/master/includes/includes.php and let me know if it fixes the problems.

**Comment by mikeleord** [comment]
oohh yes!
solved everything!
Thank you!!!

![vesta ok](https://user-images.githubusercontent.com/42770845/62488547-32cd3a00-b7cd-11e9-8382-ec0f7090e7f0.png)

**Comment by cdgco** [comment]
@mikeleord Great! Let me know if there is anything else you need help with.

**Comment by mikeleord** [comment]
Ok thanks a lot in the meantime!
